### ISSUE TITLE
Client PB Setup

### ISSUE THREAD

**Issue by Seamus-McMasters** [TROG111/Recipes#4]
I am following your instructions on setup but get a Script Error on the Client PB when Activating.  I noticed you said you need 11 Databanks, but I only count 10 in your instructions: 8 for the Database, 1 for the Menu, and 1 for the Comms.   Where is the remaining one go and what is it for?  Also, in your client linking instructions you mention "core"  what do you mean by this?  ie Core, Menu, Screens 1 2 3 , and then comms.

Ref:
Step 6: Finally, we need to link the screens and databanks to the third PB, in the following order: core, menu databank, screen 1, 2, 3, and the comms databank

**Comment by TROG111** [comment]
yeah, I think it is only 10 now as I removed 1.

core is the core of the factory (i.e. the static core) - this will cause a script error if not linked.

I am on discord (Trog #5105) which may be an easier way to give you support - although I am UTC+3 so looks like we might not be in favourable timezones)

**Comment by Seamus-McMasters** [comment]
So using DB 1_5 and Server 1_5 I was not able to get anything to display on the screens.   I removed all connections, reinstalled using 1_4 and was able to get the displays up, but not able to filter or click on anything.  Any Suggestions?  Only Screens 1 & 2 are on Screen 3 is blank.  I did check my DU Lua Library and I have the dkjson.lua file in the directory.

**Comment by TROG111** [comment]
screen 3 wont show anything until you have selected an item from the main list and it has successfully pulled it back from the database.

I suggest using v1_4 of all modules.  

You cannot click on anything on the screen if you are holding a tool, so make sure your hands are empty before trying.

I am in the process of building a modular implementation of my factory monitoring scripts including the recipe manager which will be based on a dynamic xs core which you can deploy inside your factry (or anywhere you like) and includes a factory monitoring script which using emitter/reciever will talk to the suite of factory monitoring modules.   This should ensure that in future people dont have problems linking things (as the modules will come pre-build as blueprints/compactables).

Im sorry you are having problems... promise you that it does work (I have 4 implementations working in my base)

**Comment by Seamus-McMasters** [comment]
Ok, it works now, I was holding a tool lol.  Really appreciate the quick responses!  All is working with v1_4 on all.

**Comment by TROG111** [comment]
great.... any issues please message me so I can fix ;-)
